Alert Success/Delete UI
jaimejazarenoiii/kwartracker-ios pull request #11
Opened 2021-05-05 10:45 UTC by veverlymae

# 📲 What
- Alert Success/Delete UI

# 🤔 Why
- Create Reusable AlertButton, AlertMessage and AlertImageView
- Create Alert View for Success/Delete

# 🛠 How
- N/A

# ✅ Acceptance criteria
- N/A

# ⏰ TODO
-N/A

# 🔗 References
https://xd.adobe.com/view/88019197-b52c-4c03-a717-e10207152dd7-dd52/screen/4e1b839f-e7e8-46c1-9d45-5719013ffadb/
https://xd.adobe.com/view/88019197-b52c-4c03-a717-e10207152dd7-dd52/screen/7f516a7b-f26e-4727-9f2e-05827057fbe8/
<img width="304" alt="Screen Shot 2021-05-05 at 6 39 29 PM" src="https://user-images.githubusercontent.com/77820589/117129996-06938280-add2-11eb-9034-5c936f756878.png">

2021-05-17 06:17 UTC, jaimejazarenoiii requested changes

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Reusable/ButtonView.swift
> +                HStack {
I think HStack here is unnecessary

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Reusable/ImageView.swift
> +    enum ImageType {
Actually all of these enums with success and delete can be refactored into just one enum, maybe DialogState? then you'll have two options, either make the message included in the cases or create another params per view with an additional param `message`

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Alert/AlertView.swift
> +                .frame(width: 220, height: 240, alignment: .center)
If the alert is uniform in size, move the magic numbers to a constant, and I think the height should be dynamic not fixed

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Alert/ Content/MainAlertView.swift
> +
maybe move the params here

state: DialogStatus, message: String

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Alert/ Content/MainAlertView.swift
> +            ButtonView(actionHandler: {}, actionLabel: .success)
Can create a style for the view depending on the status

2021-05-17 06:17 UTC, jaimejazarenoiii commented on Kwartracker/Scenes/Reusable/MessageView.swift
> +                return "Are you sure you want to delete this?"
I think this should be dynamic

2021-05-18 02:24 UTC, ljylaya approved these changes

2021-05-23 23:50 UTC, merged