Feature/transaction page UI
jaimejazarenoiii/kwartracker-ios pull request #12
Opened 2021-05-06 12:52 UTC by 1jacobb1

# 📲 What
- Transaction list view, page where transactions are being displayed.

# 🤔 Why
- N/A

# 🛠 How
-  N/A

# ✅ Acceptance criteria
- Unit Tests all passing.

# ⏰ TODO
- N/A

# 🔗 References
- https://gyazo.com/364705a0ee26a3d249db70432befa811

2021-05-17 10:53 UTC, jaimejazarenoiii requested changes

2021-05-18 00:06 UTC, 1jacobb1 commented on Kwartracker/Custom Components/Button Style/CircleButtonStyle.swift
> +                        Circle()
Sorry, like how? 😓

2021-05-18 01:25 UTC, 1jacobb1 commented on Kwartracker/Enums/Currency.swift
> +    case philippinePeso = "fil_PH"
Clear! I will change this to Int and then I will create a variable for string, this string is used to display currency depends on which country. 🙇

2021-05-18 02:23 UTC, ljylaya requested changes

2021-05-31 03:28 UTC, 1jacobb1 commented on Kwartracker/Scenes/Transactions/TransactionsView.swift
> +        setUpContentAppearance()
Calling this in onAppear block won't apply the UI appearance :(

2021-06-01 12:34 UTC, merged