Feature/add wallet
jaimejazarenoiii/kwartracker-ios pull request #42
Opened 2021-06-18 05:40 UTC by ljylaya

# 📲 What
- Add wallet 
- 
# 🤔 Why
- N/A

# 🛠 How
- Fill up fields on sign in / sign up

# ✅ Acceptance criteria
- N/A

# ⏰ TODO
- N/A

# 🔗 References
-

2021-06-20 04:10 UTC, 1jacobb1 requested changes

2021-06-21 01:03 UTC, ljylaya commented on Kwartracker/Custom Components/Form Inputs/KTextfield.swift
> +                   textLabel: "L10n.Wallet.Label.walletName",
I will change it. that's supposed to be temporary while fixing the conflicts

2021-06-21 08:41 UTC, ljylaya commented on Kwartracker/Custom Components/Form Inputs/KTextfield.swift
> +                   textLabel: "L10n.Wallet.Label.walletName",
@1jacobb1  it should be deleted. The reference has been removed but the file is still there.

2021-06-21 12:56 UTC, 1jacobb1 commented
Great!! 👏

2021-06-21 12:56 UTC, 1jacobb1 approved these changes

2021-06-21 12:57 UTC, merged